name: Build and deploy ASP.Net Core app to Azure Web App - edusync-api-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build EduSyncProject.csproj --configuration Release

      - name: Publish project
        run: dotnet publish EduSyncProject.csproj -c Release -o ./publish

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_77C01E4B9F514EA587E5D8357D4E0832 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_595075CD089D49D781BC99010AD06583 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8D2B5414E6A840C68A0A5AD22EAD0513 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'edusync-api-backend'
          slot-name: 'Production'
          package: ./publish
